name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - name: Build and package
        run: |
          npm ci
          npx @vscode/vsce package
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
